name: planttag
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.7.0
  image_cropper: ^3.0.2
  image_picker: ^0.8.7+3
  dio: ^5.1.1
  video_player: ^2.6.1
  get: ^4.6.5
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  google_sign_in: ^6.1.0
  cloud_firestore: ^4.5.2
  mime: ^1.0.4
  http_parser: ^4.0.2
  swipe_image_gallery: ^0.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true